server:  port: 8023

spring:
  datasource:
    url: jdbc:sqlserver://MARCOS;databaseName=DBCINEWEB    username: marquitos    password: marquitos    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver 
  jpa:    show-sql: true    properties:      hibernate:        enable_lazy_load_no_trans: true    